name: "Build"
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run format:check
      - run: npm run check-types
      - run: npm run lint
      - name: Create a .env file
        run: cp .env.example .env
      - run: npm run build
