name: "Build"
on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Build on node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run check-types
      - run: npm run lint
      - run: npm run build
